In [2]:
import numpy as np

import pandas as pd
import difflib

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
#data collection

In [16]:
data = pd.read_csv("/content/tmdb_5000_movies.csv")

In [17]:
data.head(5)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [18]:
data.shape

(4803, 20)

In [19]:
#selecting relevent feature for recommended

In [20]:
data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [21]:
select_features=["keywords","genres","tagline","tagline","overview"]
print(select_features)

['keywords', 'genres', 'tagline', 'tagline', 'overview']


In [22]:
for feature in select_features:
  data[feature]=data[feature].fillna('')

In [23]:
combined_feature =data["genres"]+' '+ data["keywords"]+' '+ data["title"]+' '+ data["tagline"]+' '+ data["overview"]
print(combined_feature)

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801    [] [] Shanghai Calling A New Yorker in Shangha...
4802    [{"id": 99, "name": "Documentary"}] [{"id": 15...
Length: 4803, dtype: object


In [24]:
vectorizer=TfidfVectorizer()

In [25]:
feature_vector=vectorizer.fit_transform(combined_feature)

print(feature_vector)

  (0, 13895)	0.09458158332630255
  (0, 10779)	0.031001338727179396
  (0, 26896)	0.09840013450258289
  (0, 25252)	0.09527056317386141
  (0, 18319)	0.08155955074993838
  (0, 12139)	0.058825006262144
  (0, 31943)	0.08903222500915235
  (0, 11929)	0.05789175926348415
  (0, 13002)	0.03657580650929757
  (0, 23952)	0.06174359972299238
  (0, 32723)	0.0915484970024896
  (0, 25149)	0.02793014264705981
  (0, 24135)	0.08857648456263686
  (0, 31850)	0.018181671966557622
  (0, 16140)	0.10625894896207388
  (0, 21288)	0.02459094756106854
  (0, 25642)	0.1138244786719881
  (0, 13519)	0.06945649777190678
  (0, 6521)	0.11652473310424102
  (0, 20734)	0.02121704586837734
  (0, 25591)	0.21563875981664485
  (0, 25059)	0.018388268547588228
  (0, 33987)	0.04213857396803621
  (0, 31604)	0.0481025679898354
  (0, 17171)	0.08431579918413541
  :	:
  (4802, 17407)	0.08065500185144257
  (4802, 25110)	0.06527567045379759
  (4802, 34127)	0.06723605281248186
  (4802, 15079)	0.2148964740530188
  (4802, 29329)	0.05595500763

In [26]:
#cosine similarity

In [27]:
similarity=cosine_similarity(feature_vector)
print(similarity)

[[1.         0.2803327  0.17222328 ... 0.142657   0.01089612 0.07400333]
 [0.2803327  1.         0.17357648 ... 0.14906021 0.03057052 0.07526348]
 [0.17222328 0.17357648 1.         ... 0.09064079 0.01064322 0.05262517]
 ...
 [0.142657   0.14906021 0.09064079 ... 1.         0.03191807 0.06851894]
 [0.01089612 0.03057052 0.01064322 ... 0.03191807 1.         0.03796331]
 [0.07400333 0.07526348 0.05262517 ... 0.06851894 0.03796331 1.        ]]


In [28]:
print(similarity.shape)

(4803, 4803)


getting movie name from the user

In [29]:
movie_name=input("enter the favorite movie name:")

enter the favorite movie name:avtar


In [30]:
title_list= data["title"].tolist()
print(title_list)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [31]:
find_close_match=difflib.get_close_matches(movie_name,title_list)
print(find_close_match)

['Avatar', 'Salvador', 'Water']


In [32]:
close_match = find_close_match[0]
print(close_match)

Avatar


In [34]:
data = data.reset_index(drop=True)
index_of_movie = data[data['title'] == close_match].index[0]
print(index_of_movie)

0


In [40]:
data.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [37]:
#getting a list of similar movie
similarity_score= list(enumerate(similarity[index_of_movie]))
print(similarity_score)
len(similarity_score)

[(0, 1.0), (1, 0.28033269614774065), (2, 0.17222327818706262), (3, 0.24518035086709186), (4, 0.3405890578781927), (5, 0.2561000951323496), (6, 0.18471463767684276), (7, 0.21190633396153352), (8, 0.1893662156353789), (9, 0.17234944172821895), (10, 0.21282547158888104), (11, 0.1367642041635382), (12, 0.2514476833766785), (13, 0.17083124752102188), (14, 0.24951314364625515), (15, 0.1843521959982385), (16, 0.23563688928314436), (17, 0.270641449049725), (18, 0.1804885957604434), (19, 0.1825636551493786), (20, 0.16550880984125127), (21, 0.15335017818648536), (22, 0.14340629173724911), (23, 0.1708403242140359), (24, 0.2097996273229067), (25, 0.19679138441420416), (26, 0.2632474378011409), (27, 0.297494474625226), (28, 0.2317570856667665), (29, 0.19028181324842605), (30, 0.20662102343639427), (31, 0.2757612472272414), (32, 0.1534870559879669), (33, 0.21264453501173616), (34, 0.17615243362486266), (35, 0.22855571344597186), (36, 0.19852154990920276), (37, 0.1922374363652732), (38, 0.15564230342

4803

In [39]:
sorted_similar_movies=sorted(similarity_score,key = lambda x:x[1],reverse= True)
print(sorted_similar_movies)

[(0, 1.0), (322, 0.40653755990429447), (2428, 0.3988341074554457), (2442, 0.395798318743249), (838, 0.3890308434749986), (2403, 0.38475686134428627), (2217, 0.38435463768964484), (95, 0.381509261069817), (305, 0.3741937800778188), (3158, 0.3738752672195853), (582, 0.36939787415257075), (123, 0.3633586930032251), (3143, 0.3621598769262423), (1068, 0.3617818872838249), (1531, 0.361731015543343), (2966, 0.357060372627212), (539, 0.35231487485188945), (778, 0.3515497662679562), (770, 0.35132326773562567), (1079, 0.35095928162618134), (2015, 0.3479721385369649), (278, 0.3448132908069665), (373, 0.34254568635853694), (1352, 0.3411632246194811), (4, 0.3405890578781927), (139, 0.34013018215826185), (149, 0.33904427841650603), (1201, 0.33564702356852727), (260, 0.3345779570602172), (677, 0.3327068961342348), (156, 0.33173842652228125), (300, 0.33033185989651376), (3746, 0.32974917308738644), (4436, 0.3294737572819355), (2897, 0.32835435155024406), (1694, 0.3273724412712049), (4225, 0.3272470698

In [46]:
print("movies suggested for you: \n")
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=data[data.index == index]['title'].values[0]
  if(i<10):

    print(i,'-',title_from_index)
    i+=1

movies suggested for you: 

1 - Avatar
2 - The Fifth Element
3 - Brooklyn's Finest
4 - Southland Tales
5 - Alien³
6 - Aliens
7 - Everyone Says I Love You
8 - Interstellar
9 - Treasure Planet


In [47]:
movie_name=input("enter the favorite movie name:")
title_list= data["title"].tolist()
find_close_match=difflib.get_close_matches(movie_name,title_list)
close_match = find_close_match[0]
similarity_score= list(enumerate(similarity[index_of_movie]))
sorted_similar_movies=sorted(similarity_score,key = lambda x:x[1],reverse= True)
print("movies suggested for you: \n")
i=1
for movie in sorted_similar_movies:
  index=movie[0]
  title_from_index=data[data.index == index]['title'].values[0]
  if(i<10):

    print(i,'-',title_from_index)
    i+=1

enter the favorite movie name:iron man
movies suggested for you: 

1 - Avatar
2 - The Fifth Element
3 - Brooklyn's Finest
4 - Southland Tales
5 - Alien³
6 - Aliens
7 - Everyone Says I Love You
8 - Interstellar
9 - Treasure Planet
